# Generated by Django 6.1.1 on 2026-10-03 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('emoji', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'collection_type',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('label', models.CharField(max_length=60)),
                ('emoji', models.CharField(max_length=8)),
                ('category_label', models.CharField(max_length=60)),
                ('model_path', models.CharField(blank=True, max_length=255, null=True)),
                ('base_power', models.SmallIntegerField()),
                ('power_growth', models.SmallIntegerField(default=5)),
                ('is_starter', models.BooleanField(default=False)),
                ('is_event_exclusive', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='collection.pokemontype')),
            ],
            options={
                'db_table': 'collection_character',
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('starter', 'Starter'), ('encounter', 'Encounter'), ('survey', 'Survey'), ('event', 'Event')], max_length=10)),
                ('nickname', models.CharField(blank=True, max_length=60, null=True)),
                ('exp', models.BigIntegerField(default=0)),
                ('is_staked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pokemons', to='collection.character')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collection_pokemon',
                'constraints': [models.CheckConstraint(condition=models.Q(('exp__gte', 0)), name='pokemon_exp_non_negative'), models.UniqueConstraint(condition=models.Q(('origin', 'starter')), fields=('user',), name='collection_pokemon_one_starter_per_user')],
            },
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(condition=models.Q(('base_power__gt', 0)), name='character_base_power_positive'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(condition=models.Q(('power_growth__gt', 0)), name='character_power_growth_positive'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(condition=models.Q(('is_starter', True), ('is_event_exclusive', True), _negated=True), name='character_starter_not_exclusive'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.UniqueConstraint(condition=models.Q(('is_starter', True)), fields=('is_starter',), name='collection_character_one_starter_species'),
        ),
    ]
