# Generated by Django 6.1.1 on 2026-10-03 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('audience', models.CharField(choices=[('resident', 'Resident'), ('org', 'Org')], max_length=10)),
                ('category', models.CharField(blank=True, choices=[('problem', 'Problem'), ('initiative', 'Initiative'), ('place', 'Place')], max_length=12, null=True)),
                ('pokestop_type', models.CharField(choices=[('report', 'Report'), ('idea', 'Idea'), ('place', 'Place'), ('ngo', 'Ngo'), ('consultation', 'Consultation')], max_length=12)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('emoji', models.CharField(max_length=8)),
                ('default_title', models.CharField(blank=True, max_length=80, null=True)),
                ('votes_required', models.SmallIntegerField(default=10)),
                ('sort_order', models.SmallIntegerField(default=0)),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='collection.character')),
            ],
            options={
                'db_table': 'scenarios_scenario',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sort_order', models.SmallIntegerField(default=0)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='scenarios.scenario')),
            ],
            options={
                'db_table': 'scenarios_section',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=150)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('select', 'Select'), ('multiselect', 'Multiselect'), ('boolean', 'Boolean'), ('tags', 'Tags'), ('date', 'Date'), ('photos', 'Photos'), ('character', 'Character'), ('choice', 'Choice'), ('rating', 'Rating')], max_length=12)),
                ('required', models.BooleanField(default=False)),
                ('hint', models.TextField(blank=True, null=True)),
                ('placeholder', models.CharField(blank=True, max_length=120, null=True)),
                ('unit', models.CharField(blank=True, max_length=16, null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('show_if_key', models.CharField(blank=True, max_length=40, null=True)),
                ('show_if_value', models.JSONField(blank=True, null=True)),
                ('sort_order', models.SmallIntegerField(default=0)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='scenarios.scenario')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='scenarios.section')),
            ],
            options={
                'db_table': 'scenarios_field',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=60)),
                ('label', models.CharField(max_length=120)),
                ('sort_order', models.SmallIntegerField(default=0)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='scenarios.field')),
            ],
            options={
                'db_table': 'scenarios_field_option',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('field', 'value'), name='field_option_value_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='scenario',
            constraint=models.UniqueConstraint(fields=('id', 'pokestop_type'), name='scenario_id_type_unique'),
        ),
        migrations.AddConstraint(
            model_name='scenario',
            constraint=models.CheckConstraint(condition=models.Q(('votes_required__gt', 0)), name='scenario_votes_required_positive'),
        ),
        migrations.AddConstraint(
            model_name='scenario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('audience', 'resident'), models.Q(models.Q(('category', 'problem'), ('pokestop_type', 'report')), models.Q(('category', 'initiative'), ('pokestop_type', 'idea')), models.Q(('category', 'place'), ('pokestop_type', 'place')), _connector='OR')), models.Q(('audience', 'org'), ('category__isnull', True), ('pokestop_type__in', ['ngo', 'consultation'])), _connector='OR'), name='scenario_type_matches_category'),
        ),
        migrations.AddConstraint(
            model_name='field',
            constraint=models.UniqueConstraint(fields=('scenario', 'field_key'), name='field_key_unique_in_scenario'),
        ),
    ]
