# Generated by Django 6.1.1 on 2026-10-03 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('collection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('age_min', models.SmallIntegerField(blank=True, null=True)),
                ('age_max', models.SmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled')], default='scheduled', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='accounts.organization')),
                ('reward_character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='collection.character')),
            ],
            options={
                'db_table': 'events_event',
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('distance_m', models.DecimalField(decimal_places=1, max_digits=9)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='events.event')),
                ('reward_pokemon', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='collection.pokemon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events_participation',
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['lat', 'lng'], name='events_event_latlng_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('title__length__gte', 3)), name='event_title_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='event_ends_after_start'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__isnull', True), ('capacity__gt', 0), _connector='OR'), name='event_capacity_positive'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('age_min__isnull', True), ('age_max__isnull', True), ('age_min__lte', models.F('age_max')), _connector='OR'), name='event_age_range'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='participation_one_per_user'),
        ),
    ]
