# Generated by Django 6.1.1 on 2026-10-03 23:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('collection', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='daily_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='daily_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('daily_from__isnull', True), ('daily_to__isnull', True)), models.Q(('daily_from__isnull', False), ('daily_to__isnull', False), ('daily_from__lt', models.F('daily_to'))), _connector='OR'), name='event_daily_window'),
        ),
    ]
