# Generated by Django 6.1.1 on 2026-10-03 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('collection', '0001_initial'),
        ('scenarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokestop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('report', 'Report'), ('idea', 'Idea'), ('place', 'Place'), ('ngo', 'Ngo'), ('consultation', 'Consultation')], max_length=12)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='open', max_length=12)),
                ('scenario_version', models.IntegerField()),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('details', models.JSONField(default=dict)),
                ('votes_for', models.IntegerField(default=0)),
                ('votes_against', models.IntegerField(default=0)),
                ('votes_required', models.SmallIntegerField()),
                ('stake_released_at', models.DateTimeField(blank=True, null=True)),
                ('stake_bonus_exp', models.IntegerField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pokestops', to=settings.AUTH_USER_MODEL)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='collection.character')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pokestops', to='accounts.organization')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pokestops', to='scenarios.scenario')),
                ('staked_pokemon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='collection.pokemon')),
            ],
            options={
                'db_table': 'pokestops_pokestop',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.CharField(max_length=255, unique=True)),
                ('content_type', models.CharField(max_length=60)),
                ('size_bytes', models.IntegerField()),
                ('width', models.SmallIntegerField(blank=True, null=True)),
                ('height', models.SmallIntegerField(blank=True, null=True)),
                ('sort_order', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pokestop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pokestops.pokestop')),
            ],
            options={
                'db_table': 'pokestops_photo',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.JSONField()),
                ('verdict', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('error', 'Error')], max_length=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=60, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='scenarios.scenario')),
                ('pokestop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_logs', to='pokestops.pokestop')),
            ],
            options={
                'db_table': 'pokestops_moderation_log',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=300)),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hidden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_comment_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='pokestops.comment')),
                ('pokestop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pokestops.pokestop')),
            ],
            options={
                'db_table': 'pokestops_comment',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=300)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('select', 'Select'), ('multiselect', 'Multiselect'), ('boolean', 'Boolean'), ('tags', 'Tags'), ('date', 'Date'), ('photos', 'Photos'), ('character', 'Character'), ('choice', 'Choice'), ('rating', 'Rating')], max_length=12)),
                ('required', models.BooleanField(default=True)),
                ('options', models.JSONField(blank=True, null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('sort_order', models.SmallIntegerField(default=0)),
                ('pokestop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='pokestops.pokestop')),
            ],
            options={
                'db_table': 'pokestops_question',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], max_length=12)),
                ('to_status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], max_length=12)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pokestop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='pokestops.pokestop')),
            ],
            options={
                'db_table': 'pokestops_status_change',
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('distance_m', models.DecimalField(decimal_places=1, max_digits=9)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('pokestop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='pokestops.pokestop')),
                ('reward_pokemon', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='collection.pokemon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pokestops_survey_response',
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='pokestops.question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='pokestops.surveyresponse')),
            ],
            options={
                'db_table': 'pokestops_survey_answer',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('for', 'For'), ('against', 'Against')], max_length=7)),
                ('exp_granted', models.IntegerField(default=0)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('distance_m', models.DecimalField(decimal_places=1, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pokestop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='pokestops.pokestop')),
                ('rewarded_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='collection.pokemon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pokestops_vote',
            },
        ),
        migrations.AddIndex(
            model_name='pokestop',
            index=models.Index(fields=['lat', 'lng'], name='pokestops_latlng_idx'),
        ),
        migrations.AddIndex(
            model_name='pokestop',
            index=models.Index(fields=['status', 'type'], name='pokestops_status_type_idx'),
        ),
        migrations.AddIndex(
            model_name='pokestop',
            index=models.Index(fields=['-created_at'], name='pokestops_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='pokestop',
            constraint=models.CheckConstraint(condition=models.Q(('lat__gte', -90), ('lat__lte', 90), ('lng__gte', -180), ('lng__lte', 180)), name='pokestop_coordinates_valid'),
        ),
        migrations.AddConstraint(
            model_name='pokestop',
            constraint=models.CheckConstraint(condition=models.Q(('title__length__gte', 3)), name='pokestop_title_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='pokestop',
            constraint=models.CheckConstraint(condition=models.Q(('votes_against__gte', 0), ('votes_for__gte', 0)), name='pokestop_votes_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='pokestop',
            constraint=models.CheckConstraint(condition=models.Q(('votes_required__gt', 0)), name='pokestop_votes_required_positive'),
        ),
        migrations.AddConstraint(
            model_name='pokestop',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type__in', ['ngo', 'consultation']), ('organization__isnull', False)), models.Q(models.Q(('type__in', ['ngo', 'consultation']), _negated=True), ('organization__isnull', True)), _connector='OR'), name='pokestop_org_for_org_types'),
        ),
        migrations.AddConstraint(
            model_name='pokestop',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type__in', ['report', 'idea']), ('staked_pokemon__isnull', False)), models.Q(models.Q(('type__in', ['report', 'idea']), _negated=True), ('staked_pokemon__isnull', True)), _connector='OR'), name='pokestop_stake_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='pokestop',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('stake_bonus_exp__isnull', True), ('stake_released_at__isnull', True)), models.Q(('stake_bonus_exp__isnull', False), ('stake_released_at__isnull', False), ('staked_pokemon__isnull', False), ('stake_bonus_exp__gte', 0)), _connector='OR'), name='pokestop_stake_release_consistent'),
        ),
        migrations.AddConstraint(
            model_name='pokestop',
            constraint=models.CheckConstraint(condition=models.Q(('rejection_reason__isnull', True), ('status', 'rejected'), _connector='OR'), name='pokestop_rejection_reason'),
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.CheckConstraint(condition=models.Q(('sort_order__gte', 0), ('sort_order__lte', 2)), name='photo_max_three'),
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.UniqueConstraint(fields=('pokestop', 'sort_order'), name='photo_pokestop_order_unique'),
        ),
        migrations.AddConstraint(
            model_name='moderationlog',
            constraint=models.CheckConstraint(condition=models.Q(('verdict', 'approved'), ('pokestop__isnull', True), _connector='OR'), name='moderation_only_approved_saved'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(('body__length__gte', 1)), name='comment_body_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('pokestop', 'question_key'), name='question_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('pokestop', 'sort_order'), name='question_order_unique'),
        ),
        migrations.AddConstraint(
            model_name='statuschange',
            constraint=models.CheckConstraint(condition=models.Q(('from_status', models.F('to_status')), _negated=True), name='status_change_differs'),
        ),
        migrations.AddConstraint(
            model_name='surveyresponse',
            constraint=models.UniqueConstraint(fields=('pokestop', 'user'), name='survey_one_per_user'),
        ),
        migrations.AddConstraint(
            model_name='surveyanswer',
            constraint=models.UniqueConstraint(fields=('response', 'question'), name='survey_answer_unique'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('pokestop', 'user'), name='pokestops_vote_one_per_user'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.CheckConstraint(condition=models.Q(('exp_granted__gte', 0)), name='vote_exp_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.CheckConstraint(condition=models.Q(('distance_m__gte', 0)), name='vote_distance_non_negative'),
        ),
    ]
