# Generated by Django 6.1.1 on 2026-10-03 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokestops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pokestop',
            name='custom_fields',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pokestop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='pokestops.pokestop')),
            ],
            options={
                'db_table': 'pokestops_update',
                'indexes': [models.Index(fields=['pokestop', '-created_at'], name='pokestops_update_stop_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('title__length__gte', 1)), name='update_title_not_blank')],
            },
        ),
    ]
