# Generated by Django 6.1.1 on 2026-10-03 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(db_column='password_hash', max_length=255)),
                ('display_name', models.CharField(max_length=60)),
                ('role', models.CharField(choices=[('resident', 'Resident'), ('org', 'Org'), ('admin', 'Admin')], default='resident', max_length=10)),
                ('is_guest', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login_at', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_user',
                'constraints': [models.CheckConstraint(condition=models.Q(('is_guest', True), models.Q(('email__isnull', False), models.Q(('password', ''), _negated=True)), _connector='OR'), name='user_registered_has_credentials'), models.CheckConstraint(condition=models.Q(('is_guest', False), ('role', 'resident'), _connector='OR'), name='user_guest_is_resident')],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('kind', models.CharField(choices=[('ngo', 'Ngo'), ('foundation', 'Foundation'), ('association', 'Association'), ('city_office', 'City Office'), ('district_council', 'District Council'), ('municipality', 'Municipality'), ('other', 'Other')], max_length=20)),
                ('krs', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('suspended', 'Suspended')], default='pending', max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_organization',
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor')], default='editor', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_organization_member',
            },
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('verification_status', 'verified'), ('verified_at__isnull', False)), models.Q(models.Q(('verification_status', 'verified'), _negated=True), ('verified_at__isnull', True)), _connector='OR'), name='organization_verified_has_date'),
        ),
        migrations.AddConstraint(
            model_name='organizationmember',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='organization_member_unique'),
        ),
    ]
