# Generated by Django 6.1.1 on 2026-10-03 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('collection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField()),
                ('power', models.IntegerField()),
                ('xp_reward', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('defeated', 'Defeated'), ('expired', 'Expired')], default='active', max_length=10)),
                ('spawned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('defeated_at', models.DateTimeField(blank=True, null=True)),
                ('defeated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'game_encounter',
            },
        ),
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('distance_m', models.DecimalField(decimal_places=1, max_digits=9)),
                ('accuracy_m', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('client_time', models.DateTimeField(blank=True, null=True)),
                ('pokemon_power_total', models.IntegerField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('won', 'Won'), ('lost', 'Lost'), ('too_far', 'Too Far'), ('rejected', 'Rejected'), ('expired', 'Expired')], max_length=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reward_pokemon', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='collection.pokemon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacks', to='game.encounter')),
            ],
            options={
                'db_table': 'game_attack',
            },
        ),
        migrations.CreateModel(
            name='EnemyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('emoji', models.CharField(max_length=8)),
                ('description', models.TextField(blank=True, default='')),
                ('action_kind', models.CharField(choices=[('checkin', 'Checkin'), ('photo', 'Photo'), ('qr', 'Qr'), ('dwell', 'Dwell')], default='checkin', max_length=10)),
                ('action_label', models.CharField(max_length=200)),
                ('min_level', models.SmallIntegerField(default=1)),
                ('max_level', models.SmallIntegerField(default=5)),
                ('base_power', models.IntegerField()),
                ('power_growth', models.IntegerField(default=10)),
                ('base_xp', models.IntegerField()),
                ('spawn_weight', models.SmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enemy_types', to='collection.pokemontype')),
            ],
            options={
                'db_table': 'game_enemy_type',
            },
        ),
        migrations.AddField(
            model_name='encounter',
            name='enemy_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='game.enemytype'),
        ),
        migrations.CreateModel(
            name='PlayerProgress',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='progress', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('xp', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'game_player_progress',
                'constraints': [models.CheckConstraint(condition=models.Q(('xp__gte', 0)), name='progress_xp_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='AttackPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_used', models.IntegerField()),
                ('type_multiplier_applied', models.DecimalField(decimal_places=2, default=1, max_digits=3)),
                ('exp_gained', models.IntegerField(default=0)),
                ('attack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to='game.attack')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='collection.pokemon')),
            ],
            options={
                'db_table': 'game_attack_pokemon',
                'constraints': [models.UniqueConstraint(fields=('attack', 'pokemon'), name='attack_pokemon_unique'), models.CheckConstraint(condition=models.Q(('power_used__gt', 0)), name='attack_pokemon_power_positive'), models.CheckConstraint(condition=models.Q(('type_multiplier_applied__gte', 1)), name='attack_pokemon_multiplier_valid'), models.CheckConstraint(condition=models.Q(('exp_gained__gte', 0)), name='attack_pokemon_exp_non_negative')],
            },
        ),
        migrations.AddIndex(
            model_name='attack',
            index=models.Index(fields=['user', '-created_at'], name='game_attack_user_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='attack',
            constraint=models.UniqueConstraint(condition=models.Q(('outcome', 'won')), fields=('encounter',), name='game_attack_one_win_per_encounter'),
        ),
        migrations.AddConstraint(
            model_name='attack',
            constraint=models.CheckConstraint(condition=models.Q(('distance_m__gte', 0)), name='attack_distance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='enemytype',
            constraint=models.CheckConstraint(condition=models.Q(('min_level__gte', 1), ('min_level__lte', models.F('max_level'))), name='enemy_level_range'),
        ),
        migrations.AddConstraint(
            model_name='enemytype',
            constraint=models.CheckConstraint(condition=models.Q(('base_xp__gt', 0)), name='enemy_xp_positive'),
        ),
        migrations.AddConstraint(
            model_name='enemytype',
            constraint=models.CheckConstraint(condition=models.Q(('base_power__gt', 0), ('power_growth__gt', 0)), name='enemy_power_positive'),
        ),
        migrations.AddConstraint(
            model_name='enemytype',
            constraint=models.CheckConstraint(condition=models.Q(('spawn_weight__gt', 0)), name='enemy_weight_positive'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['status', 'lat', 'lng'], name='game_encounter_state_pos_idx'),
        ),
        migrations.AddConstraint(
            model_name='encounter',
            constraint=models.CheckConstraint(condition=models.Q(('level__gte', 1), ('level__lte', 100)), name='encounter_level_range'),
        ),
        migrations.AddConstraint(
            model_name='encounter',
            constraint=models.CheckConstraint(condition=models.Q(('power__gt', 0)), name='encounter_power_positive'),
        ),
        migrations.AddConstraint(
            model_name='encounter',
            constraint=models.CheckConstraint(condition=models.Q(('xp_reward__gt', 0)), name='encounter_xp_positive'),
        ),
    ]
