# Generated by Django 6.1.1 on 2026-10-03 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncounterCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('populated_at', models.DateTimeField(blank=True, null=True)),
                ('refill_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'game_encounter_cell',
            },
        ),
        migrations.AddConstraint(
            model_name='attack',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('outcome__in', ['won', 'lost']), ('pokemon_power_total__isnull', False)), models.Q(models.Q(('outcome__in', ['won', 'lost']), _negated=True), ('pokemon_power_total__isnull', True)), _connector='OR'), name='attack_power_total_required'),
        ),
        migrations.AddConstraint(
            model_name='attack',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('outcome', 'won'), ('reward_pokemon__isnull', False)), models.Q(models.Q(('outcome', 'won'), _negated=True), ('reward_pokemon__isnull', True)), _connector='OR'), name='attack_reward_iff_won'),
        ),
        migrations.AddConstraint(
            model_name='encountercell',
            constraint=models.UniqueConstraint(fields=('row', 'col'), name='game_encounter_cell_unique'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='game.encountercell'),
        ),
    ]
