# Generated by Django 6.1.1 on 2026-10-03 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('game', '0002_encounter_cells'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerLocation',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('accuracy_m', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='gps', max_length=10)),
                ('reported_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'game_player_location',
            },
        ),
        migrations.RemoveConstraint(
            model_name='encountercell',
            name='game_encounter_cell_unique',
        ),
        migrations.AddField(
            model_name='encounter',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encountercell',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['user', 'status'], name='game_encounter_user_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='encountercell',
            constraint=models.UniqueConstraint(fields=('user', 'row', 'col'), name='game_encounter_cell_user_unique'),
        ),
    ]
